# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Busch Jäger iNet Radio
version: "1.0.0"
slug: example
description: Home Assistant Add-On for controlling Busch Jäger iNet Radio
url: "https://github.com/gunzebe/home-assistant-addons/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
