# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Busch Jäger iNet Radio
version: "1.0.0"
slug: example
description: Home Assistant Add-On for controlling Busch Jäger iNet Radio
url: "https://github.com/gunzebe/home-assistant-addons/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  host:
    required: true
    description: 192.168.178.50
    type: string
  port:
    required: true
    description: 80
    type: integer
    default: 80
services:
  start:
    description: Start the Busch Jäger iNet Radio Add-On
  stop:
    description: Stop the Busch Jäger iNet Radio Add-On
  restart:
    description: Restart the Busch Jäger iNet Radio Add-On
  status:
    description: Get the status of the Busch Jäger iNet Radio Add-On
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"