# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Busch J채ger iNet Radio
version: "1.0.1"
slug: example
description: Home Assistant Add-On for controlling Busch J채ger iNet Radio
url: "https://github.com/gunzebe/home-assistant-addons/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  host:
    required: true
    description: The IP address or hostname of the Busch J채ger iNet Radio
    type: string
  port:
    required: true
    description: The port number of the Busch J채ger iNet Radio web interface
    type: integer
    default: 80
schema:
  host: "str?"
  port: int
